openapi: '3.0.2'
info:
  title: Create Agency API
  version: '1.0'
servers:
  - url: https://localhost:3000

paths:
  /agency:
    post:
      summary: 'Creates agency'
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              type: object
              properties:
                license:
                  type: string
                name:
                  type: string
              required:
                - "license"
                - "name"


      responses:
        '200':
          description: OK
      





  
